name: CI

on: [push]

jobs:
  build_upload_bom:
    name: "Build UploadBom"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
      
    - name: Install Task Dependencies 
      run: npm install

    - name: Install UploadBOM Dependencies 
      run: npm install
      working-directory: UploadBOM
    
    - name: Package task
      run: npm run package
