name: CI/CD - Production

on:
  release:
    types: [created]

jobs:
  build_package:
    name: "Build and Package Extention"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
      
    - name: Install Task Dependencies 
      run: npm install -g tfx-cli

    - name: Build UploadBOM Task
      run: |
        npm install
        npm run build
        npm prune --production
      working-directory: UploadBOM

    - name: Update Extension information
      run: |
        npm install
        node version-bump.js --token ${{ secrets.marketplace_access_token }} --release-type prod
    
    - name: Package task
      run: tfx extension create --output-path PackageOutput
    
    - name: Upload vsix Artifact
      uses: actions/upload-artifact@v1
      with:
        name: Extension-Package
        path: PackageOutput
  
  publish_marketplace:
    name: "Publish to VS Marketplace"
    needs: build_package
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
        
      - name: Install Dependencies 
        run: npm install -g tfx-cli

      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: Extension-Package
          path: package
      
      - name: Publish to marketplace
        run: |
          find ./package -name '*.vsix' -exec tfx extension publish -- --publisher gsoft -t ${{ secrets.marketplace_access_token }} --vsix {} \;